[package]
name = "redumper-extract-rw"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gf256 = { version = "0.3", features = ["rs"] }
